### ISSUE TITLE
Better structure of .js files

### ISSUE THREAD

**Issue by hassehulabeck** [hassehulabeck/mixer#13]
Break up the index.js into two files. The part regarding dark mode should be in a separate module or file.

**Comment by munnokd** [comment]
Can you assign this task to me?

**Comment by hassehulabeck** [comment]
Hi.

Thanks for your interest in this project. I would gladly assign this task to you, weren't it for the fact that I'm planning to let my students use it as training. Probably should mention it somewhere...

May I ask how you found it? Good-first-issue? Searched for pair-programming?

All the best.

Hans Andersson


7 mars 2023 11:49:02 Kalp Prajapati ***@***.***>:

**Comment by hassehulabeck** [comment]
On second thought, why not? Please, welcome to contribute!

**Comment by munnokd** [comment]
Thank you for assign this task to me. I will work upon this issue.
